### ISSUE TITLE
Failed to build 0.2 : yaml.h not found

### ISSUE THREAD

**Issue by ptitfred** [input-output-hk/stack2nix#112]
_Spoiler alert: I'm a Nix noob_

I've tried building the last release (commit 3d6bc24ec9b076ab854bf3b420e6c2b92d6c2924) on my machine.

I've previously build 0.1.3.1 successfully.

The error in 0.2 is pretty straightforward:

```
$ nix-build
... truncated ...
Preprocessing library for yaml-0.8.32..
Building library for yaml-0.8.32..
[ 1 of 11] Compiling Paths_yaml       ( dist/build/autogen/Paths_yaml.hs, dist/build/Paths_yaml.o )
[ 2 of 11] Compiling Text.Libyaml     ( src/Text/Libyaml.hs, dist/build/Text/Libyaml.o )
[ 3 of 11] Compiling Data.Yaml.Parser ( src/Data/Yaml/Parser.hs, dist/build/Data/Yaml/Parser.o )
[ 4 of 11] Compiling Data.Yaml.Internal ( src/Data/Yaml/Internal.hs, dist/build/Data/Yaml/Internal.o )
[ 5 of 11] Compiling Data.Yaml.Include ( src/Data/Yaml/Include.hs, dist/build/Data/Yaml/Include.o )
[ 6 of 11] Compiling Data.Yaml.Builder ( src/Data/Yaml/Builder.hs, dist/build/Data/Yaml/Builder.o )
[ 7 of 11] Compiling Data.Yaml.Pretty ( src/Data/Yaml/Pretty.hs, dist/build/Data/Yaml/Pretty.o )
[ 8 of 11] Compiling Data.Yaml        ( src/Data/Yaml.hs, dist/build/Data/Yaml.o )
[ 9 of 11] Compiling Data.Yaml.TH     ( src/Data/Yaml/TH.hs, dist/build/Data/Yaml/TH.o )
[10 of 11] Compiling Data.Yaml.Config ( src/Data/Yaml/Config.hs, dist/build/Data/Yaml/Config.o )
[11 of 11] Compiling Data.Yaml.Aeson  ( src/Data/Yaml/Aeson.hs, dist/build/Data/Yaml/Aeson.o )
[ 1 of 11] Compiling Paths_yaml       ( dist/build/autogen/Paths_yaml.hs, dist/build/Paths_yaml.p_o )
[ 2 of 11] Compiling Text.Libyaml     ( src/Text/Libyaml.hs, dist/build/Text/Libyaml.p_o )
[ 3 of 11] Compiling Data.Yaml.Parser ( src/Data/Yaml/Parser.hs, dist/build/Data/Yaml/Parser.p_o )
[ 4 of 11] Compiling Data.Yaml.Internal ( src/Data/Yaml/Internal.hs, dist/build/Data/Yaml/Internal.p_o )
[ 5 of 11] Compiling Data.Yaml.Include ( src/Data/Yaml/Include.hs, dist/build/Data/Yaml/Include.p_o )
[ 6 of 11] Compiling Data.Yaml.Builder ( src/Data/Yaml/Builder.hs, dist/build/Data/Yaml/Builder.p_o )
[ 7 of 11] Compiling Data.Yaml.Pretty ( src/Data/Yaml/Pretty.hs, dist/build/Data/Yaml/Pretty.p_o )
[ 8 of 11] Compiling Data.Yaml        ( src/Data/Yaml.hs, dist/build/Data/Yaml.p_o )
[ 9 of 11] Compiling Data.Yaml.TH     ( src/Data/Yaml/TH.hs, dist/build/Data/Yaml/TH.p_o )
[10 of 11] Compiling Data.Yaml.Config ( src/Data/Yaml/Config.hs, dist/build/Data/Yaml/Config.p_o )
[11 of 11] Compiling Data.Yaml.Aeson  ( src/Data/Yaml/Aeson.hs, dist/build/Data/Yaml/Aeson.p_o )

In file included from c/helper.c:4:0: error: 

c/helper.h:4:10: error:
     fatal error: yaml.h: No such file or directory
     #include <yaml.h>
              ^~~~~~~~
  |
4 | #include <yaml.h>
  |          ^
compilation terminated.
`cc' failed in phase `C Compiler'. (Exit code: 1)
builder for '/nix/store/5mkx89jx7y5bpz4l7l4vassld3m3xn2b-yaml-0.8.32.drv' failed with exit code 1
cannot build derivation '/nix/store/qlgkipxxzh1asvfyi4j7fw3m5ag1k93x-cabal2nix-2.10.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/93flmxzr2493lz7vndia9byfagfa6l91-stack-1.7.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/w6ai9gc8gpz4bw2bm12la8k3g6fldylb-stack2nix-0.1.3.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/w6ai9gc8gpz4bw2bm12la8k3g6fldylb-stack2nix-0.1.3.1.drv' failed
```

I'm sure you guys have already tested it on your machines, and I'm not sure how to reproduce it :/
Any chance stack is polluting my setup?

I'll be happy to do more tests, or test commands you might suggest :)

**Comment by domenkozar** [comment]
Hey @ptitfred what is your nixpkgs commit? It's picked from `NIX_PATH`.

**Comment by ptitfred** [comment]
95a8cb3ade1ad0e2649f0f3128e90c53964af5e1

**Comment by ptitfred** [comment]
and
```
$ cat .version
18.09
```

**Comment by ptitfred** [comment]
I've just `nix-channel --update` and reproduced. nixpkgs revision `d7d31fea7e7eef8ff4495e75be5dcbb37fb215d0`

**Comment by domenkozar** [comment]
Should be fixed with https://github.com/NixOS/nixpkgs/commit/059c2312be70ce5734ffa7c4bf3f1973a8d25236

Explanation: configuration-nix is what stack2nix uses, configuration-common should have options that are tied to versions. It's currently one of the bits that is hard to maintain, but I see no alternatives yet.

**Comment by domenkozar** [comment]
Please reopen if error persists :)

**Comment by ptitfred** [comment]
I guess I'll have to wait for unstable to be updated, it's a bit lagging behind git

**Comment by puffnfresh** [comment]
I'm on 18.03, is that commit going to be backported?

**Comment by ptitfred** [comment]
I honestly have no clue :/

https://github.com/NixOS/nixpkgs-channels/tree/nixpkgs-unstable has been updated recently but I still don't get how it's all working

**Comment by domenkozar** [comment]
@puffnfresh done :)

**Comment by puffnfresh** [comment]
Oh sorry I didn't realise the project is pinned. I updated nixpkgs-src.json to master and it's working.
